apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: linkerd-sp-validator-webhook-config
  labels:
    linkerd.io/control-plane-component: sp-validator
    linkerd.io/control-plane-ns: linkerd
webhooks:
- name: linkerd-sp-validator.linkerd.io
  namespaceSelector:
    matchExpressions:
    - key: config.linkerd.io/admission-webhooks
      operator: NotIn
      values:
      - disabled
  clientConfig:
    service:
      name: linkerd-sp-validator
      namespace: linkerd
      path: "/"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lSQU0yaldKMWZ0V2lHV0dOZjE0Wlg5SjB3RFFZSktvWklodmNOQVFFTEJRQXcKS3pFcE1DY0dBMVVFQXhNZ2JHbHVhMlZ5WkMxemNDMTJZV3hwWkdGMGIzSXViR2x1YTJWeVpDNXpkbU13SGhjTgpNakF3TnpJek1URTBOVFV3V2hjTk1qRXdOekl6TVRFME5UVXdXakFyTVNrd0p3WURWUVFERXlCc2FXNXJaWEprCkxYTndMWFpoYkdsa1lYUnZjaTVzYVc1clpYSmtMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVAKQURDQ0FRb0NnZ0VCQU1CUEhCRHVqVVBLazE5QkZSWGdLVVFBZnhMNExSQ29ibnJwbmx3MUVqWXI4cnRjYk1PTgp4aUpJcGFnclU2VWZKWU50eklMT0llWEFCR091TWFWUXkyN0k1NjBBN216Qi8zOGNIb3NMczJVcHlMRVhycFp6CitpWmtDc09kTnhpRkhGVVdvMm5TVlJlMVdUbWMzWElvSWRqaHdkdDR4NlJQU2xBc3l0RGF0R2dienkrUndFK3oKVzVDM0RBL2g1YnFnZmZWb0IyTmR1MlBOZlBCUWxUUUdTMm1WeTJmTkEzRkRFenJ3OTlINDVPTThjNTVVZHFkSgo4ejYzLzRkTDduS2JIN1RjVHVoSmxLSzRWeFduNEN5ZGFCTVphaE8rUmg3WWZYaFNwQ3JzaHlMaWhkV2ljUUtxCnBVNlFSRUZYbnI0N1ZlNDlFaWlXQ0JoN25lK0VUdHRWcDRNQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUUQKQWdLa01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBRApBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDR0JzZXc3YXNrOXIyYXJubGdIL25LZFhrcTF0SS9DbUxlCnl0b2xsdHdqd2FVUjFyd0JKczVISGo0MEVVcG5Pb3NXdXJqY1NuWU1OWXFXREcxQ3ZCdEJrcUEyK0F3M0xZRWMKZzZya0ZLeFl6ZnFJOGFyNGljWk5JR1dMSGhlS09qVG1DUkFuMWR0LzErbWk4dFhCR04rK2s0Nlo2RE5QdFFsSwpyeVI0NDZUSGx0eFFLKzBLZmVnTHgvQmhEZkwyVklQNnlQMC9NSE1wb056WnNPSWRScjhuTkc0QzA4aUJUeVlvClFhUGxTcm00bzM4cEZSVDVrRnh6WGdUR1dhS0g0VVQzcFBFdEdjRWVPdW9ub0ZYMjZMc2VJcExNMi9XUEpna3YKendsTFdFcXhrTjhKUUtnNmNsY1RSajlJUzFnS0ZJdmdxZzZ4OWNFQ25tcTFHY0FKbXBYcwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  failurePolicy: Ignore
  rules:
  - operations: [ "CREATE" , "UPDATE" ]
    apiGroups: ["linkerd.io"]
    apiVersions: ["v1alpha1", "v1alpha2"]
    resources: ["serviceprofiles"]
  sideEffects: None